### ISSUE TITLE
[Update Request] Gramps 5.2.3-2

### ISSUE THREAD

**Issue by sjsajj** [tunisiano187/choco-packages#27]
the script for gramps needs to use the correct windows installer link which is https://github.com/gramps-project/gramps/releases/download/v5.2.3/GrampsAIO-5.2.3-2_win64.exe currently its using https://github.com/gramps-project/gramps/releases/download/v5.2.3/GrampsAIO-5.2.3-1_win64.exe

**Version requested**
5.2.3-2
https://github.com/gramps-project/gramps/releases/download/v5.2.3/GrampsAIO-5.2.3-2_win64.exe

**Comment by tunisiano187** [comment]
I have a problem pushing it to the repository : 504 (Gateway Time-out)...
if you want to install it, the nupkg is there : https://we.tl/t-nrQsDVBU4R

I'm still searching why it doesn't work

**Comment by tunisiano187** [comment]
OK, i found the solution, the - was causing an error, so i've updated it to ..
It will be available soon.
