### ISSUE TITLE
[Update Request] minecraft-education

### ISSUE THREAD

**Issue by teknowledgist** [tunisiano187/choco-packages#36]
The version that downloads is 1.21.500 which has a different checksum.

The main site [still says 1.21.03](https://education.minecraft.net/en-us/get-started/download), but [the What's New page](https://edusupport.minecraft.net/hc/en-us/sections/360009898252-Product) does indicate that the v1.21.05 was released 2024-09-03.

Thanks for maintaining this package!

**Comment by tunisiano187** [comment]
Hello,
Thanks for the information.
I'm taking the version from the url directly.
I've updated my script to use the direct url of the file as it seems working now.
i'm still testing, but i'll publish it asap.
you can see the updated script here : https://github.com/tunisiano187/choco-packages/blob/minecraft-new-update/automatic/minecraft-education/update.ps1

**Comment by tunisiano187** [comment]
Done, pushed to the community
